channels_to_keep:
  CD117: CD117
  CD11c: CD11C
  CD123: CD123
  CD127: CD127
  CD15: CD15
  CD16: CD16
  CD19: CD19
  CD21: CD21
  CD25: CD25
  CD3: CD3
  CD31: CD31
  CD36: CD36
  CD38: CD38
  CD4: CD4
  CD45: CD45
  CD45RA: CD45RA
  CD49f: CD49f
  CD56: CD56
  CD57: CD57
  CD66: CD66
  CD69: CD69
  CD7: CD7
  CD8: CD8
  FAP: FAP
  FOXP3: FOXP3
  PDL1: PDL1
  Vimentin: VIMENTIN
  panCK: PANCK
